name: Mirror to Codeberg

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository to Codeberg
        uses: yesolutions/mirror-action@v0.6.0
        with:
          REMOTE: "https://codeberg.org/${{ secrets.CODEBERG_USERNAME }}/ClipAssistant.git"
          GIT_USERNAME: "${{ secrets.CODEBERG_USERNAME_ME }}"
          GIT_PASSWORD: "${{ secrets.CODEBERG_TOKEN }}"
